language: java
jdk:
- openjdk7
- oraclejdk8
os:
  - linux
env:
  matrix:
    - NEO4J_VERSION=2.2.5
    - NEO4J_VERSION=2.3.0-RC1
script: "mvn clean test -Dneo4j.version=${NEO4J_VERSION}"
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - cat $TRAVIS_SSH_KEY > deploy_key.gem
  - chmod 600 deploy_key.pem # this key should have push access
  - ssh-add deploy_key.pem
  - if [[ "$NEO4J_VERSION" == "2.2.5" && "$TRAVIS_JDK_VERSION" == "openjdk7" &&  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn clean site; fi
notifications:
  email:
    on_success: never
    on_failure: change
