language: java
jdk:
- openjdk7
- oraclejdk8
os:
  - linux
env:
  matrix:
    - NEO4J_VERSION=2.2.5
    - NEO4J_VERSION=2.3.0-RC1
before_install:
  - openssl aes-256-cbc -K $encrypted_db5709a4bccd_key -iv $encrypted_db5709a4bccd_iv -in .travis-key.enc -out .travis-key -d
script: "mvn clean test -Dneo4j.version=${NEO4J_VERSION}"
after_success:
  - git config --global user.email "travis@bsimard.com"
  - git config --global user.name "Travis CI"
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis-key
  - ssh-add .travis-key
  - if [[ "$NEO4J_VERSION" == "2.2.5" && "$TRAVIS_JDK_VERSION" == "openjdk7" &&  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn clean site; fi
notifications:
  email:
    on_success: never
    on_failure: change
